title: "Yumi Heo | Data Scientist"
# author: Yumi Heo
email: yumi.heo.01@gmail.com
description: >-
 Data Scientist currently based in London
theme: minima

header_pages:
  - cv.md
  - projects.md

github_username: yumi-h-1

minima:
  social_links:
    github: yumi-h-1
    linkedin: yumi-h

exclude:
  - .DS_Store
  - README.md
